services:
  retrieve:
    container_name: retrieve
    build:
      args:
        PORT: 8005
        SRC_DIR: retrieve
        DENSE_INDEX: 1
        SPARSE_LITE_INDEX: 0
      context: .
      dockerfile: retrieve/Dockerfile
    volumes:
      - "./retrieve:/src"
      - ~/.deeppavlov:/root/.deeppavlov
    ports:
      - 8005:8005
    environment:
      - CUDA_VISIBLE_DEVICES=7
  
  text-based-generation:
    container_name: text-based-generation
    build:
      args:
        PORT: 8006
        SRC_DIR: text_based_generation
        RETRIEVE_ENDPOINT: http://retrieve:8005/respond
      context: .
      dockerfile: text_based_generation/Dockerfile
    volumes:
      - "./text_based_generation:/src"
      - ~/.deeppavlov:/root/.deeppavlov
    ports:
      - 8006:8006
    environment:
      - CUDA_VISIBLE_DEVICES=7

  graph-based-generation:
    container_name: graph-based-generation
    build:
      args:
        PORT: 8007
        SRC_DIR: graph_based_generation
        KBQA_ENDPOINT: http://kbqa:8008/respond
      context: .
      dockerfile: graph_based_generation/Dockerfile
    volumes:
      - "./graph_based_generation:/src"
      - ~/.deeppavlov:/root/.deeppavlov
    ports:
      - 8007:8007
    environment:
      - CUDA_VISIBLE_DEVICES=7
    
  llm-based-generation:
    container_name: llm-based-generation
    build:
      args:
        PORT: 8009
        SRC_DIR: llm_based_generation
        KBQA_ENDPOINT: http://kbqa:8008/respond
        MODEL_NAME: lmsys/vicuna-13b-v1.3
        PROMPT_STYLE: fewshot_triplets
        QUANTIZED: 1
      context: .
      dockerfile: llm_based_generation/Dockerfile
    volumes:
      - "./llm_based_generation:/src"
      - ~/.cache:/root/.cache
    ports:
      - 8009:8009
    environment:
      - CUDA_VISIBLE_DEVICES=6

  kbqa:
    container_name: kbqa
    build:
      args:
        PORT: 8009
        SRC_DIR: kbqa
        LAN: EN
        FACTOID_CLF: 1
      context: .
      dockerfile: kbqa/Dockerfile
    volumes:
      - "./kbqa:/src"
      - ~/.deeppavlov:/root/.deeppavlov
    ports:
      - 8009:8009
    environment:
      - CUDA_VISIBLE_DEVICES=4
  
  factoid-classification:
    container_name: factoid_classification
    build:
      args:
        PORT: 8010
        SRC_DIR: factoid_classification
      context: .
      dockerfile: factoid_classification/Dockerfile
    volumes:
      - "./factoid_classification:/src"
      - ~/.deeppavlov:/root/.deeppavlov
    ports:
      - 8010:8010
    environment:
      - CUDA_VISIBLE_DEVICES=4


version: '3.7'
